chore: unit test for LocalValue with some docs for the functions
fido-id/localvalue-ts pull request #9
Opened 2021-10-01 15:20 UTC by ranpafin

Closes #1

2021-10-01 15:40 UTC, fes300 requested changes
wonderful :1st_place_medal: 
just a few minor changes

2021-10-01 15:40 UTC, fes300 commented on src/LocalValue.ts
> + * @category constructors
wouldn't folds be "destructors" based on your taxonomy?

2021-10-01 15:40 UTC, fes300 commented on src/LocalValue.ts
> + * @category constructors
wouldn't folds be "destructors" based on your taxonomy?

2021-10-01 15:40 UTC, fes300 commented on src/LocalValue.ts
> + * @category Applicative
:love_letter:

2021-10-01 15:40 UTC, fes300 commented on src/LocalValue.ts
> + * @category Functor
:heart:

2021-10-01 15:40 UTC, fes300 commented on src/LocalValue.ts
> + * Transforms an Either to an LocalValue discarding the error.
it is not actually discarding the value but wrapping it into an `invalid`

2021-10-01 15:40 UTC, fes300 commented on src/__tests__/localValue.spec.tsx
> +
this empty line shouldn't be here, did you run prettier?

2021-10-03 08:28 UTC, ranpafin commented on src/__tests__/localValue.spec.tsx
> +
actually no, i was under the impression the hook took care of that, running it manually fixed many things. I think we may need to review the hook as it gives (a false) greenlight on format.

2021-10-03 08:28 UTC, ranpafin commented on src/LocalValue.ts
> + * Transforms an Either to an LocalValue discarding the error.
yes!

2021-10-03 08:28 UTC, ranpafin commented on src/LocalValue.ts
> + * @category constructors
100% agree

2021-10-03 08:28 UTC, ranpafin commented on src/LocalValue.ts
> + * @category constructors
100% agree

2021-10-03 08:34 UTC, fes300 approved these changes
💯

2021-10-04 07:32 UTC, merged